
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";
import MobileNavbar from "../components/MobileNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/icon.svg" sizes="any" />
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}>
        <div className="min-h-screen bg-white">
          {/* Sidebar solo en desktop */}
          <div className="hidden md:fixed md:inset-y-0 md:left-0 md:block md:w-64 md:z-20">
            <Navbar />
          </div>
          <main className="flex-1 p-1 md:p-4 bg-white transition-all duration-300 md:pl-64">
            <div className="w-full max-w-5xl mx-auto">{children}</div>
          </main>
          {/* Navbar móvil solo en mobile */}
          <MobileNavbar />
        </div>
      </body>
    </html>
  );
}
